### ISSUE TITLE
USER STORY: General info

### ISSUE THREAD

**Issue by faridjos** [faridjos/restaurant#1]
As a **site user** I can **find general information about the restaurant** so that **I can decide if I want to eat there**

## Acceptance Criteria
* Acceptance Criteria 1: Picture of a restaurant on the home page
* Acceptance Criteria 2: About section on the home page

## Tasks
- [x] Task 1: Write base.html
- [x] Task 2: Find picture
- [x] Task 3: Write some text in the About section
