### ISSUE TITLE
USER STORY: Booking form

### ISSUE THREAD

**Issue by faridjos** [faridjos/restaurant#11]
As a **site user** I can **fill out an online form** so that **I can choose a date and time for my visit**

## Acceptance Criteria
* Acceptance Criteria 1: The form has the fields for the first name, second name, username, party size, and booking time

## Tasks
- [x] Task 1: Create a form class that inherits from the customer and booking classes
- [x] Task 2: Write the view code
- [x] Task 3: Create the template to render the form
- [x] Task 3: Connect up the URL
