### ISSUE TITLE
USER STORY: View booking

### ISSUE THREAD

**Issue by faridjos** [faridjos/restaurant#12]
As a **site user** I can **view the booking** so that **I know my booking is confirmed**

## Acceptance Criteria
* Acceptance Criteria 1: The booking can be stored in the database. (C in CRUD)
* Acceptance Criteria 2: The user can view his booking. (R in CRUD)
* Acceptance Criteria 3: The application searches for free seats before the booking is made. If there are no free seats, the user is redirected to the booking form.

## Tasks
- [x] Task 1: Store the booking in the database
- [x] Task 2: Write view first assuming there is no other booking. Create template and URL pattern
- [x] Task 3: Add view code taking into account the occupancy of the tables.
