### ISSUE TITLE
USER STORY: Account registration

### ISSUE THREAD

**Issue by faridjos** [faridjos/restaurant#6]
As a **site user** I can **register an account** so that **I can update or delete a booking**

## Acceptance Criteria
* Acceptance Criteria 1: The user can register an account, sign in/sign out
* Acceptance Criteria 2: An authenticated user can view his booking
## Tasks
- [x] Task 1: Install allauth
- [x] Task 2: Style signup, login, and logout pages
- [x] Task 3 Create a view to enable an authenticated user to access his booking
